# https://doc.traefik.io/traefik/reference/static-configuration/file/
# https://github.com/ChristianLempa/boilerplates/blob/main/docker-compose/traefik/config/traefik.yaml
# https://technotim.live/posts/crowdsec-traefik/
#
#
#
# ------------------------------------- Global
global:
  checkNewVersion: false
  sendAnonymousUsage: false
# ------------------------------------- Servers Transport
#serversTransport:
#  insecureSkipVerify: true
#  rootCAs:
#    - foobar
#    - foobar
#  maxIdleConnsPerHost: 42
#  forwardingTimeouts:
#    dialTimeout: 42s
#    responseHeaderTimeout: 42s
#    idleConnTimeout: 42s
# ------------------------------------- Entry Points
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: "https"
          scheme: "https"
  https:
    address: ":443"
#    http:
#      middlewares:
#        - crowdsec-bouncer@file
    http2:
      maxConcurrentStreams: 42
    http3:
      advertisedPort: 42
#    udp:
#      timeout: 42s
# ------------------------------------- Providers
providers:
  providersThrottleDuration: 42s
  file:
    directory: /path/to/config
    watch: true
    #filename: foobar
    debugLogGeneratedTemplate: true
# ------------------------------------- API
api:
  insecure: true
  dashboard: true
#  debug: true
#  disabledashboardad: false
# ------------------------------------- Metrics
#metrics:
#  prometheus:
#    buckets:
#      - 42
#      - 42
#    addEntryPointsLabels: true
#    addRoutersLabels: true
#    addServicesLabels: true
#    entryPoint: foobar
#    manualRouting: true
#    headerLabels:
#      label1: foobar
#      label2: foobar
# ------------------------------------- Log
log:
  level: info
#  filePath: foobar
#  format: foobar
# ------------------------------------- Accesslog
#accessLog:
#  filePath: foobar
#  format: foobar
#  filters:
#    statusCodes:
#      - foobar
#      - foobar
#    retryAttempts: true
#    minDuration: 42s
#  fields:
#    defaultMode: foobar
#    names:
#      name0: foobar
#      name1: foobar
#    headers:
#      defaultMode: foobar
#      names:
#        name0: foobar
#        name1: foobar
#  bufferingSize: 42
# ------------------------------------- Tracing
#tracing:
#  serviceName: foobar
#  spanNameLimit: 42
#  jaeger:
#    samplingServerURL: foobar
#    samplingType: foobar
#    samplingParam: 42
#    localAgentHostPort: foobar
#    gen128Bit: true
#    propagation: foobar
#    traceContextHeaderName: foobar
#    disableAttemptReconnecting: true
#    collector:
#      endpoint: foobar
#      user: foobar
#      password: foobar
# ------------------------------------- Certificates Resolvers
certificatesResolvers:
  staging:
    acme:
      email: your-email@example.com
      storage: /path/to/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: your-resolver (e.g. cloudflare)
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
  production:
    acme:
      email: your-email@example.com
      storage: /path/to/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: your-resolver (e.g. cloudflare)
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# ------------------------------------- Certificates
experimental:
  kubernetesGateway: true
  http3: true
#  plugins:
#    # https://plugins.traefik.io/plugins/6335346ca4caa9ddeffda116/crowdsec-bouncer-traefik-plugin
#    crowdsec-bouncer-traefik-plugin:
#      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
#      version: "v1.2.1-rc1"
