http:
# ------------------------------------- Routers
  routers:
    dashboard:
      entryPoints:
        - "https"
      rule: "Host(`dashboard.example.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: dashboard
# ------------------------------------- Services
  services:
    dashboard:
      loadBalancer:
        servers:
          - url: "http://192.168.0.100"
        passHostHeader: true
# ------------------------------------- Middlewares
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
    # https://plugins.traefik.io/plugins/6335346ca4caa9ddeffda116/crowdsec-bouncer-traefik-plugin
    my-crowdsec-bouncer-traefik-plugin:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          CrowdsecLapiKey: 40796d93c2958f9e58345514e67740e5
          Enabled: "false"


    default-whitelist:
      ipWhiteList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    very-secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers
